# Generated by Django 5.2.10 on 2026-01-23 13:10

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name or organization name', max_length=200)),
                ('email', models.EmailField(help_text='Email address for receipts and communication', max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number with country code (e.g., +254712345678)', max_length=128, null=True, region=None)),
                ('country', django_countries.fields.CountryField(help_text="Donor's country", max_length=2)),
                ('city', models.CharField(blank=True, help_text='City or town', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Full address (optional)')),
                ('donor_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate/Organization'), ('anonymous', 'Anonymous')], default='individual', help_text='Type of donor', max_length=15)),
                ('is_international', models.BooleanField(default=False, help_text='True if donor is outside Kenya')),
                ('preferred_currency', models.CharField(default='KES', help_text='Preferred donation currency (KES, USD, EUR, GBP)', max_length=3)),
                ('newsletter_subscription', models.BooleanField(default=True, help_text='Whether donor wants to receive updates')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount donated (in KES)', max_digits=12)),
                ('donation_count', models.IntegerField(default=0, help_text='Number of donations made')),
                ('first_donation_date', models.DateTimeField(blank=True, help_text='Date of first donation', null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, help_text='Date of most recent donation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='donors_dono_email_17ddb3_idx'), models.Index(fields=['country'], name='donors_dono_country_4eb036_idx'), models.Index(fields=['-total_donations'], name='donors_dono_total_d_2568d8_idx')],
            },
        ),
    ]
