# Generated by Django 5.2.10 on 2026-01-23 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the support category (e.g., Education Support)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of this support area')),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-graduation-cap' for FontAwesome)", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Optional image representing this category', null=True, upload_to='categories/')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount donated to this category (in KES)', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently accepting donations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Category',
                'verbose_name_plural': 'Support Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in original currency', max_digits=10)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', help_text='Currency code (KES, USD, EUR, GBP)', max_length=3)),
                ('amount_in_kes', models.DecimalField(decimal_places=2, help_text='Donation amount converted to KES for reporting', max_digits=10)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa')], help_text='How the donor paid (PayPal or M-Pesa)', max_length=10)),
                ('transaction_id', models.CharField(help_text='Unique transaction reference from payment gateway', max_length=200, unique=True)),
                ('paypal_order_id', models.CharField(blank=True, help_text='PayPal order ID', max_length=200, null=True)),
                ('paypal_payer_email', models.EmailField(blank=True, help_text="PayPal payer's email", max_length=254, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa transaction receipt number', max_length=100, null=True)),
                ('mpesa_phone_number', models.CharField(blank=True, help_text='Phone number used for M-Pesa payment', max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of this donation', max_length=10)),
                ('payment_response', models.JSONField(blank=True, help_text='Full payment gateway response (for debugging)', null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When donation was initiated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('receipt_sent', models.BooleanField(default=False, help_text='Whether receipt email has been sent')),
                ('receipt_number', models.CharField(blank=True, help_text='Unique receipt number', max_length=50)),
                ('donor', models.ForeignKey(help_text='The donor who made this donation', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donor')),
                ('support_category', models.ForeignKey(help_text='Which area this donation supports', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.supportcategory')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa')], help_text='Which payment gateway was used', max_length=10)),
                ('action', models.CharField(help_text="Action performed (e.g., 'create_order', 'stk_push', 'callback')", max_length=100)),
                ('request_payload', models.JSONField(blank=True, help_text='Data sent to payment gateway', null=True)),
                ('response_payload', models.JSONField(blank=True, help_text='Response received from payment gateway', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code from gateway', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the operation was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, help_text='Associated donation (if created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-created_at'], name='donations_d_created_7012d0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method'], name='donations_d_payment_ef61a1_idx'),
        ),
    ]
